import { ReleaseState } from "../enums/releaseState";

 export let comorbiditiList = [
  "I05.0 Stenoza mitrala",
  "I10 Hipertensiunea esentiala (primara)",
  "I25.9 Cardiopatie ischemica cronica, nespecificata",
  "I34.0 Insuficienta mitrala (valva)",
  "I35.1 Insuficienta (valva) aortica",
  "I48 Fibrilatia atriala si flutter",
  "I50.0 Insuficienta cardiaca congestiva",
  "K44.9 Hernia diafragmatica fara obstructie sau gangrena",
  "K76.0 Degenerescenta grasoasa a ficatului, neclasificata altundeva",
  "M47.99 Spondiloza, localizare nespecificata",
  "U07.1 COVID-19 cu virus identificat",
  "E11.9 Diabet mellitus tip 2 fara complicatii",
  "E66.0 Obezitate datorita unui exces caloric",
  "J96.0 Insuficienta respiratorie acuta",
  "E87.6 Hipopotasemie",
  "F01.9 Dementa vasculara",
  "H91.9 Pierderea auzului",
  "I49.8 Alte aritmii cardiace specificate",
  "M47.95 Spondiloza, regiune toraco-lombara",
  "E11.65 Diabet mellitus tip 2 cu control slab",
  "E78.2 Hiperlipidemie mixta",
  "E87.5 Hiperpotasemie",
  "G20 Boala Parkinson",
  "I63.8 Alte infarcte cerebrale",
  "N17.9 Insuficienta renala acuta",
  "R74.8 Nivele anormale ale altor enzime serice",
  "E11.8 Diabet mellitus tip 2 cu complicatii nespecificate",
  "I67.8 Alte boli cerebrovasculare, specificate",
  "K12.1 Alte forme de stomatite",
  "N40 Hiperplazia prostatei",
  "R94.5 Rezultate anormale ale explorarilor functionale hepatice",
  "D69.6 Trombocitopenia",
  "I74.9 Embolia si tromboza unor artere nespecificate",
  "J43.9 Emfizem, nespecificat",
  "B97.2 Coronavirusi, cauza unor boli clasificate la alte capitole",
  "D64.9 Anemia",
  "D69.5 Trombocitopenia secundara",
  "E03.9 Hipotiroidia",
  "F33.9 Tulburare depresiva recurenta",
  "I11.9 Cardiopatia hipertensiva fara insuficienta (congestiva) a inimii",
  "I25.8 Alte forme de cardiopatie ischemica cronica",
  "I27.2 Alte hipertensiuni pulmonare secundare",
  "I36.1 Insuficienta nereumatismala (valva) tricuspida",
  "I50.9 Insuficienta cardiaca",
  "N18.8 Alta insuficienta renala cronica",
  "E86 Hipovolemia, deshidratarea",
  "I70.8 Ateroscleroza altor artere",
  "M47.90 Spondiloza, localizari multiple in coloana vertebrala",
  "R09.1 Pleurezie",
  "I25.11 Cardiopatia aterosclerotica a arterei coronariene native",
  "J18.9 Pneumonie",
  "R09.2 Stop respirator",
  "D51.8 Alte anemii prin carenta de vitamana B12",
  "E06.3 Tiroidita autoimuna",
  "M06.90 Artrita reumatoida, localizari multiple",
  "E66.9 Obezitate",
  "F92.0 Tulburare de conduita depresiva",
  "C76.1 Tumora maligna torace",
  "C90.00 Mielom multiplu, fara mentionarea remisiunii",
  "F41.9 Tulburare anxioasa",
  "I49.3 Depolarizare ventriculara prematura",
  "I82.8 Embolia si tromboza altor vene specificate",
  "B34.0 Infectia adenovirala",
  "B34.2 Infectia coronavirala",
  "D46.7 Alte sidroame mielodisplazice",
  "I46.9 Stop cardiac",
  "I44.7 Bloc al ramurii stangi",
  "A41.9 Sepsis",
  "E87.2 Acidoza",
  "F03 Dementa nespecificata",
  "I44.0 Bloc atrio-ventricular, primul grad",
  "I45.1 Alte blocuri ale ramurii drepte a fascicolului si nespecificate",
  "J12.8 Alte pneumonii virale",
  "J69.8 Pneumopatii datorite inhalatiei altor substante solide si lichide",
  "M05.39+ Artrita reumatoida cu implicarea altor organe sau sisteme",
  "R40.2 Coma",
  "E11.69 Diabet mellitus tip 2 cu alte complicatii specificate",
  "E78.4 Alte hiperlipidemii",
  "E78.1 Hipergliceridemia esentiala",
  "G51.8 Alte afectiuni ale nervului facial",
  "G81.0 Hemiplegia flasca",
  "R73 Nivel ridicat al glucozei in sange",
  "I25.5 Cardiomiopatie ischemica",
  "K21.9 Boala refluxului gastro-esofagian fara esofagita",
  "N18.90 Insuficienta renala cronica nespecificata",
  "Z90.5 Absenta dobandita a rinichiului",
  "A09 Diareea si gastro-enterita probabil infectioase",
  "I47.1 Tahicardia supraventriculara",
  "K75.2 Hepatita reactiva nespecifica",
  "L89 Ulceratia de decubitus",
  "I20.0 Angina instabila",
  "I25.2 Infarct miocardic vechi",
  "J44.9 Boala pulmonara obstructiva cronica",
  "Z44.9 Amplasarea si ajustarea unui dispozitiv prostetic extern nespecificat",
  "I70.9 Ateroscleroza generalizata si nespecificata",
  "K57.30 Diverticuloza intestinului gros fara perforatie sau abces si fara mentionarea hemoragiei",
  "K80.20 Calcul al vezicii biliare fara colecistita, fara mentionare obstructiei",
  "R74.0 Crestere a nivelelor transaminazei si dehidrogeneza acidului lactic [LDH]",
  "D68.3 Tulburari hemoragice datorita anticoagulantelor circulante",
  "Z92.4 Istoric personal de interventii chirurgicale majore, neclasificate altundeva",
  "D18.08 Hemangiom, alte localizari",
  "Z72.1 Consumul de alcool",
  "E87.0 Hiperosmolaritate si hipernatremie",
  "F01.3 Dementa vasculara mixta, corticala si subcorticala",
  "F05.9 Delir nespecificat",
  "I50.1 Insuficienta ventriculara stanga",
  "J96.1 Insuficienta respiratorie cronica",
  "K80.11 Calcul al vezicii biliare cu o alta forma de colecistita, cu obstructie",
  "R00.0 Tahicardie",
  "Z63.6 Dependenta de nevoia de ingrijiri acasa",
  "B37.9 Candidiaza, fara precizare",
  "F06.7 Tulburari cognitive usoare",
  "F41.1 Tulburare de anxietate generalizata",
  "G45.8 Alte atacuri ischemice cerebrale tranzitorii si sindroame inrudite",
  "I07.1 Insuficienta tricuspida",
  "I20.9 Angina pectorala",
  "I24.8 Alte forme de cardiopatie ischemica acuta",
  "I72.0 Anevrismul arterei carodite",
  "J44.0 Boala pulmonara obstructiva cronica cu infectie acuta a cailor respiratorii inferioare",
  "J47 Bronsiectazia",
  "J84.1 Alte boli pulmonare interstitiale cu fibroza",
  "N39.0 Infectia tractului urinar, cu localizare nespecificata",
  "D29.1 Tumora benigna prostata",
  "D64.8 Alte anemii specificate",
  "I44.4 Bloc fascicular anterior stang",
  "I64 Ictus, nespecificat ca hemoragic sau ca infarct",
  "R52.2 Alt tip de durere cronica",
  "B18.1 Hepatita virala cronica B fara agent Delta",
  "M41.84 Alte forme de scolioza, regiune toracica",
  "R16.1 Splenomegalie",
  "E14.9 Diabet mellitus nespecificat fara complicatii",
  "I15.8 Alte hipertensiuni secundare",
  "J18.0 Bronhopneumonie",
  "M06.98 Artrita reumatoida, alta localizare",
  "I35.0 Stenoza (valva) aortica",
  "J12.9 Pneumonia virala",
  "B90.9 Sechelele tuberculozei respiratorii si nespecificate",
  "I26.9 Embolia vaselor pulmonare fara mentiunea cordului pulmonar acut",
  "Y44.2 Anticoagulante",
  "I84.9 Hemoroizi nespecificati fara complicatii",
  "I87.2 Insuficienta venoasa (cronica) (periferica)",
  "K63.50 Polip al colonului",
  "M10.99 Guta",
  "N20.9 Litiaza urinara",
  "Z86.6 Istoric personal de boli ale sistemului nervos si organelor de simt",
  "J18.1 Pneumonia lobara",
  "K59.1 Diareea functionala",
  "J45.9 Astm",
  "B67.0 Infectia ficatului cu Echinococcus granulosus",
  "K26.7 Ulcerul duodenal, cronic fara hemoragie sau perforatie",
  "K40.90 Hernia inghinala unilaterala sau nespecificata, fara obstructie sau gangrena, nespecificata ca recidivanta",
  "R06.6 Sughit",
  "I06.1 Insuficienta aortica reumatismala",
  "E10.9 Diabet mellitus tip 1 fara complicatii",
  "I27.0 Hipertensiunea pulmonara primara",
  "Z92.1 Istoric personal de utilizare (actuala) pe termen lung de anticoagulante",
  "Z95.1 Prezenta unei grefe de bypass aorto-coronarian",
  "Z95.2 Prezenta unei prosteze de valva a inimii",
  "Z45.0 Ajustarea si intretinerea unui stimulator cardiac",
  "K85 Pancreatita acuta",
  "M41.59 Alta scolioza secundara",
  "N21.0 Litiaza vezicala",
  "E10.65 Diabet mellitus tip 1 cu control slab",
  "E78.5 Hiperlipidemia",
  "I47.2 Tahicardia ventriculara",
  "I49.5 Sindromul de boala sinusala",
  "I51.9 Cardiopatia",
  "M16.9 Coxartroza",
  "M17.9 Gonartroza",
  "M47.89 Alte spondiloze",
  "R41.8 Alte simptome si semne referitoare la functiile cognitive si constienta si nespecificate",
  "R79.8 Alte rezultate anormale specificate ale chimiei sangelui",
  "D63.8* Anemia in cursul altor boli cronice clasificate altundeva",
  "E46 Malnutritia proteino-energetica nespecificata",
  "I46.0 Stop cardiac cu resuscitare reusita",
  "J18.8 Alte pneumonii, cu micro-organisme nespecificate",
  "N18.0 Boala renala in stadiul final",
  "Z99.2 Dependenta de dializa renala",
  "E87.1 Hipo-osmolaritate si hiponatremie",
  "J43.8 Alte emfizeme",
  "J98.5 Bolile mediastinului",
  "N21.8 Alte litiaze [calculi] ale cailor urinare inferioare",
  "N28.1 Chistul rinichiului, dobandit",
  "I69.3 Sechelele infarctului cerebral",
  "Q50.12 Chist ovarian in dezvoltare, multiplu",
  "Z90.7 Absenta dobandita a organului(lor) genital(e)",
  "I70.22 Ateroscleroza arterelor extremitatilor cu durere la repaos",
  "I73.8 Alte boli vasculare periferice",
  "K82.8 Alte boli specificate ale vezicii biliare",
  "M47.94 Spondiloza",
  "M51.3 Alta deteriorare a unui alt disc intervertebral specificat",
  "D52.8 Alte anemii prin carenta de acid folic",
  "E21.1 Hiperparatiroidism secundar, neclasificat altundeva",
  "I45.0 Bloc fascicular drept",
  "I77.1 Stenoza arterelor",
  "K58.9 Sindromul intestinului iritabil fara diaree",
  "L50.8 Alte forme de urticarie",
  "M16.0 Coxartroza primara, bilaterala",
  "M46.80 Alte spondilopatii inflamatorii specificate",
  "M77.5 Alte entezopatii ale piciorului",
  "M89.81 Alte boli specificate ale oaselor, regiunea umarului",
  "Q25.3 Stenoza aortei",
  "Y84.1 Dializa renala",
  "I42.0 Cardiomiopatia cu dilatatie",
  "G35 Scleroza multipla",
  "I80.2 Flebita si tromboflebita altor vase profunde ale extremitatilor inferioare",
  "D62 Anemia post-hemoragica acuta",
  "E11.22 Diabet mellitus tip 2 cu nefropatie diabetica stabilita",
  "J41.0 Bronsita cronica simpla",
  "K25.0 Ulcerul gastric, acut cu hemoragie",
  "Y84.6 Sondaj urinar",
  "Z86.5 Istoric personal al altor tulburari mentale si de comportament",
  "Z86.7 Istoric personal de boli ale aparatului circulator",
  "D12.5 Tumora benigna colon sigmoid",
  "E04.2 Gusa multinodulara netoxica",
  "G31.9 Afectiuni degenerative ale sistemului nervos, nespecificate",
  "S06.02 Pierdere a cunostintei pe o durata scurta [mai putin de 30 minute]",
  "K25.9 Ulcerul gastric,nespecificat ca acut sau cronic, fara hemoragie sau perforatie",
  "D52.9 Anemia prin carenta de acid folic",
  "S22.40 Fracturi multiple de coaste",
  "Z86.11 Istoric personal de tuberculoza",
  "D50.8 Alte anemii prin carenta de fier",
  "M48.24 Artroza interspinoasa",
  "E21.2 Alte hiperparatiroidisme",
  "E83.3 Tulburari de metabolism al fosforului",
  "E83.5 Tulburari de metabolism al calciului",
  "Q61.3 Rinichi polichistic",
  "M10.90 Guta",
  "E07.8 Alte afectiuni specificate ale tiroidei",
  "E66.2 Obezitate extrema cu hipoventilatie alveolara",
  "E87.3 Alcaloza",
  "K52.9 Gastroenterita si colita neinfectioase",
  "L30.9 Dermatita",
  "I83.9 Vene varicoase ale extremitatilor inferioare fara ulceratie sau inflamatie",
  "I31.3 Efuziune pericardica (neinflamatorie)",
  "R06.0 Dispnee",
  "R11 Greata si voma",
  "R51 Cefalee",
  "R57.8 Alt tip de soc",
  "I70.0 Ateroscleroza aortei",
  "K86.2 Chistul pancreasului",
  "K86.9 Boala pancreasului",
  "M41.95 Scolioza",
  "D75.2 Trombocitoza esentiala",
  "I49.1 Depolarizare atriala prematura",
  "L40.9 Psoriazis",
  "M47.84 Alte spondiloze",
  "D46.4 Anemie refractara",
  "E83.4 Tulburari de metabolism al magneziului",
  "M10.00 Guta idiopatica",
  "J80 Sindrom de suferinta respiratorie la adult",
  "K81.0 Colecistita acuta",
  "T79.7 Emfizem subcutanat traumatic",
  "E58 Carenta alimentara de calciu",
  "E61.2 Carenta de magneziu",
  "Z88.8 Istoric personal de alergie la alte droguri, medicamente si substante biologice",
  "G46.7* Alte sindroame lacunare (I60-I67+)",
  "S15.00 Leziune a carotidei",
  "T50.9 Alte droguri, medicamente si substante biologice si nespecificate",
  "Z95.9 Prezenta de implante si de grefe cardiace si vasculare",
  "Z85.5 Istoric personal de tumora maligna a tractului urinar",
  "C34.9 Tumora maligna bronhii si pulmon ",
  "J90 Revarsare pleurala",
  "I11.0 Cardiopatia hipertensiva cu insuficienta (congestiva) a inimii",
  "L50.1 Urticaria idiopatica",
  "M81.50 Osteoporoza idiopatica",
  "E88.9 Tulburari metabolice",
  "F51.0 Insomnie neorganica",
  "F60.6 Tulburare de personalitate anxioasa [evitanta]",
  "I20.8 Alte forme de angina pectorala",
  "K42.9 Hernia ombilicala fara obstructie sau gangrena",
  "M43.04 Spondiloliza",
  "M48.26 Artroza interspinoasa, regiune lombara",
  "N83.2 Alte chisturi ale ovarului si nespecificate",
  "Z85.6 Istoric personal de leucemie",
  "N60.9 Displazia mamara benigna",
  "R77.8 Alte anormalitati specificate ale proteinelor plasmatice",
  "M10.09 Guta idiopatica",
  "M41.94 Scolioza",
  "A46 Erizipelul",
  "E03.2 Hipotiroidia datorita unor medicamente si altor substante exogene",
  "E66.8 Alte obezitati",
  "G47.32 Sindromul apneei de somn obstructive",
  "I31.8 Alte boli specificate ale pericardului",
  "I83.0 Vene varicoase cu ulceratie ale extremitatilor inferioare",
  "K20 Esofagita",
  "K29.7 Gastrita",
  "K70.9 Boala alcoolica a ficatului",
  "K74.0 Fibroza hepatica",
  "K86.1 Alte pancreatite cronice",
  "M84.28 Intarziere in consolidarea unei fracturi, altele",
  "Z87.2 Istoric personal de boli ale pielii si tesutului celular subcutanat",
  "Z87.4 Istoric personal de boli ale aparatului genito-urinar",
  "Z95.0 Prezenta unui stimulator cardiac",
  "I70.21 Ateroscleroza arterelor extremitatilor cu claudicatie intermitenta",
  "Z97.8 Prezenta altor dispozitive specificate",
  "D52.0 Anemia prin carenta alimentara de acid folic",
  "F44.7 Tulburari disociative [de conversie] mixte",
  "G25.9 Tulburari extrapiramidale si de motricitate",
  "G64 Alte tulburari ale sistemului nervos periferic",
  "H54.0 Cetitatea ambilor ochi",
  "J37.0 Laringita cronica",
  "K29.3 Gastrita superficiala cronica",
  "K30 Dispepsia",
  "N26 Rinichi scleros nespecificat",
  "E44.1 Malnutritia proteino-energetica usoara",
  "I25.6 Ischemie silentioasa a miocardului",
  "I79.8* Alte boli ale arterelor, arteriolelor si capilarelor in boli clasificate altundeva",
  "N13.2 Hidronefroza cu obstructie calculoasa renala si ureterala",
  "N20.1 Litiaza ureterului",
  "N23 Colica nefritica nespecificata",
  "C61 Tumora maligna a prostatei",
  "C67.9 Tumora maligna vezica urinara",
  "I73.9 Boala vasculara periferica",
  "N13.8 Alta uropatie obstructiva si cu reflux",
  "Y83.5  Amputatia de membru(e)",
  "E78.0 Hipercolesterolemie esentiala",
  "F33.0 Tulburare depresiva recurenta, episod actual usor",
  "K57.32 Diverticulita intestinului gros fara perforatie sau abces si fara mentionarea hemoragiei",
  "K58.0 Sindromul intestinului iritabil cu diaree",
  "T88.7 Efect advers nespecificat al unui drog sau medicament",
  "Z88.1 Istoric personal de alergie la alte antibiotice",
  "D35.0 Tumora benigna suprarenala",
  "K59.0 Constipatia",
  "M45.04 Spondilita anchilozanta",
  "N31.0 Vezica urinara neuropatica neinhibata, neclaificata altundeva",
  "D25.9 Leiomiom al uterului",
  "E79.0 Hiperuricemia fara semne de artrita inflamatorie sau de boala tofacee",
  "F41.0 Tulburare de panica [anxietate episodica paroxistica]",
  "K26.3 Ulcerul duodenal, acut fara hemoragie sau perforatie",
  "K40.20 Hernia inghinala bilaterala, fara obstructie si gangrena",
  "K71.0 Boala toxica a ficatului cu colestaza",
  "Z95.5 Prezenta de implant si grefa de angioplastie coronariana",
  "I63.9 Infarctul cerebral",
  "M81.99 Osteoporoza",
  "H91.3 Surdo-mutitate",
  "I49.0 Fibrilatia ventriculara si flutter",
  "I51.7 Cardiomegalia",
  "M47.93 Spondiloza, regiune toraco-cervicala",
  "R59.9 Ganglioni limfatici mariti, nespecificati",
  "R05 Tuse",
  "Z85.3 Istoric personal de tumora maligna a sanului",
  "Z90.1 Absenta dobandita a sinului(lor)",
  "B96.1 Klebsiella pneumoniae [K. pneumoniae], cauza unor boli clasate la alte capitole",
  "D18.03 Hemangiom, structuri ale sistemului hepatobiliar si pancreas",
  "N11.1 Pielonefrita obstructiva cronica",
  "N27.0 Rinichi mic, unilateral",
  "Z85.4 Istoric personal de tumora maligna a organelor genitale",
  "C34.2 Tumora maligna lobul mijlociu, bronhii si pulmon",
  "C78.7 Tumora maligna secundara a ficatului",
  "C79.7 Tumora maligna secundara a glandei suprarenale",
  "D63.0* Anemia in bolile neoplazice",
  "E04.1 Nodul tiroidian unic, netoxic",
  "I31.1 Pericardita cronica constrictiva",
  "I69.4 Sechelele ictusului, nespecificat ca hemoragie sau infarct",
  "M41.05 Scolioza idiopatica infantila",
  "Q85.0 Neurofibromatoza (nemaligna)",
  "T78.8 Alte efecte adverse",
  "I95.9 Hipotensiune",
  "A04.7 Enterocolita prin Clostridium difficile",
  "E11.23 Diabet mellitus tip 2 cu boala renala stadiu final [ESRD]",
  "G40.90 Epilepsia, fara epilepsie intractabila",
  "G81.1 Hemiplegia spastica",
  "I63.3 Infarctul cerebral datorita trombozei arterelor cerebrale",
  "R00.1 Bradicardie",
  "C50.9 Tumora maligna san",
  "D53.9 Anemia nutritionala",
  "E10.52 Diabet mellitus tip 1 cu angiopatie periferica, cu gangrena",
  "B18.9 Hepatita virala cronica",
  "R12 Pirozis",
  "F45.1 Tulburare somatoforma nediferentiata",
  "I41.1* Miocardita in bolile virale, clasificate altundeva",
  "E87.4 Tulburari mixte ale echilibrului acido-bazic",
  "F69 Tulburare nespecificata de personalitate si de comportament la adult",
  "I74.2 Embolia si tromboza arterelor extremitatilor superioare",
  "N13.3 Hidronefroza, alta si nespecificata",
  "N18.91 Deficienta renala cronica",
  "N81.1 Cistocel",
  "N81.8 Alt prolaps genital la femeie",
  "R31 Hematuria nespecificata",
  "R57.1 Soc hipovolemic",
  "M06.49 Poliatropatia inflamatorie",
  "I13.2 Cardio-nefropatia  hipertensiva cu insuficienta cardiaca (congestiva) si renala",
  "N20.0 Calculii rinichiului",
  "R50.9 Febra",
  "H28.2* Cataracta in alte boli clasificate altundeva",
  "H36* Afectiuni retiniene in boli clasificate altundeva",
  "I32.1* Pericardita in alte boli infectioase si parazitare clasificata altundeva",
  "Z87.18 Istoric personal de alte boli ale aparatului digestiv",
  "E20.9 Hipoparatiroidism",
  "K76.9 Boala ficatului",
  "B18.2 Hepatita virala cronica C",
  "E13.65 Alte forme specificate de diabet mellitus cu control slab",
  "N17.8 Alta insuficienta renala acuta",
  "J45.0 Astmul cu predominenta alergica",
  "G93.4 Encefalopatia",
  "I98.20* Varice esofagiene in boli clasificate altundeva fara sangerare",
  "K74.6 Alta ciroza a ficatului si nespecificata",
  "R18 Ascita",
  "J98.4 Alte modificari pulmonare",
  "M47.92 Spondiloza, regiune cervicala",
  "I45.5 Alte blocuri cardiace specificate",
  "Z85.0 Istoric personal de tumora maligna a aparatului digestiv",
  "I84.1 Hemoroizi interni cu alte complicatii",
  "K62.0 Polip anal",
  "M20.1 Hallux valgus (dobandit)",
  "M47.96 Spondiloza",
  "I49.9 Aritmia cardiaca",
  "M32.8 Alte forme de lupus sistemic eritematos",
  "J32.0 Sinuzita maxilara cronica",
  "J32.2 Sinuzita etmoidala cronica",
  "S06.01 Pierdere a cunostintei pe o durata nespecificata",
  "Z88.9 Istoric personal de alergie la droguri, medicamente si substante biologice nespecificate",
  "A41.51 Sepsis datorit Escherichia coli [E. Coli]",
  "A41.52 Sepsis datorit pseudomonas",
  "C48.1 Tumora maligna localizari precise ale peritoneului",
  "C56 Tumora maligna a ovarului",
  "D01.5 Carcinom in situ ficat , vezicula si caile biliare",
  "D06.9 Carcinom in situ col uterin",
  "R60.0 Edem localizat",
  "T78.4 Alergie",
  "G45.9 Atac ischemic cerebral tranzitoriu",
  "G93.9 Afectiune cerebrala",
  "I34.2 Stenoza (valvei) mitrala nereumatismala",
  "Z86.0 Istoric personal de alte tumori maligne",
  "E11.29 Diabet mellitus tip 2 cu alte complicatii renale specificate",
  "B17.8 Alte hepatite virale acute specificate",
  "H54.7 Pierdere de vedere",
  "S98.1 Amputatie traumatica a unui deget de la picior",
  "T82.7 Infectie si reactie inflamatorie datorita altor dispozitive, implanturi si grefe cardiace si vasculare",
  "F41.2 Tulburare anxioasa si depresiva mixta",
  "I25.0 Boala cardio-vasculara aterosclerotica, astfel descrisa",
  "G40.10 Epilepsia simptomatica legata de localizare (focala, partiala) si sindroame epileptice cu atacuri partiale simple",
  "L50.0 Urticaria alergica",
  "Z88.0 Istoric personal de alergie la penicilina",
  "C64 Tumora maligna a rinichiului, cu exceptia bazinetului renal",
  "I27.9 Cardiopatia pulmonara",
  "I70.24 Ateroscleroza arterelor extremitatilor cu gangrena",
  "Z89.4 Absenta dobandita a piciorului si gleznei",
  "Z99.9 Dependenta de folosirea unei masini si dispozitiv medical nespecificate",
  "I71.9 Anevrismul aortic, fara mentiunea rupturii",
  "K80.21 Calcul al vezicii biliare fara colecistita",
  "R04.2 Hemoptizie",
  "C48.2 Tumora maligna peritoneu",
  "C78.0 Tumora maligna secundara a pulmonului",
  "D69.8 Alte afectiuni hemoragice specificate",
  "I30.9 Pericardita acuta",
  "E03.8 Alte hipotiroidii specificate",
  "F20.8 Alte forme de schizofrenie",
  "D72.8 Alte anomalii specificate ale celulelor albe",
  "M47.80 Alte spondiloze",
  "R76.8 Alte rezultate imunologice anormale specificate ale serului",
  "Z99.1 Dependenta de un aparat de respiratie",
  "E11.42 Diabet mellitus tip 2 cu polineuropatie diabetica",
  "C16.9 Tumora maligna stomac ",
  "F45.39 Disfunctie autonoma somatoforma, organe sau sisteme multiple",
  "R58 Hemoragie",
  "E21.3 Hiperparatiroidism",
  "N19 Insuficienta renala nespecificata",
  "M51.9 Afectiunea unui disc intervertebral",
  "D50.9 Anemia prin carenta de fier",
  "K43.9 Hernia ventrala fara ocluzie sau gangrena",
  "J96.9 Insuficienta respiratorie",
  "M41.34 Scolioza prin anomalie toracica",
  "M10.98 Guta",
  "E05.9 Tireotoxicoza",
  "C24.1 Tumora maligna ampula Vater",
  "C25.9 Tumora maligna pancreas ",
  "E16.2 Hipoglicemie nespecificata",
  "Z96.68 Prezenta altor implanturi ale articulatiilor ortopedice",
  "D50.0 Anemia prin carenta de fier secundara unei pierderi de sange (cronica)",
  "D58.9 Anemie hemolitica ereditara",
  "G54.4 Afectiunile radiculare lombo-sacrale",
  "G56.0 Sindromul canalului carpian",
  "I84.5 Hemoroizi externi fara complicatii",
  "K29.5 Gastrita cronica",
  "K87.0* Tulburari ale vezicii biliare si cailor biliare in boli clasificate altundeva",
  "M67.82 Alte afectiuni specificate ale sinoviei si tendonului, brat",
  "B97.1 Enterovirusi",
  "D41.0 Tumora rinichi cu evolutie imprevizibila si necunoscuta",
  "N28.9 Tulburare a rinichiului si a ureterului",
  "Z43.6 Supravegherea altor orificii artificiale ale tractului urinar",
  "E75.6 Tulburari ale lipidelor de rezerva",
  "E11.34 Diabet mellitus tip 2 cu alte retinopatii",
  "R04.0 Epistaxis",
  "H90.4 Surditate neurosensoriala unilaterala fara alterarea auditiei celeilalte urechi",
  "M10.06 Guta idiopatica, picior parte inferioara",
  "M17.0 Gonartroza primara",
  "B37.0 Stomatita prin Candida",
  "H40.8 Alte glaucoame",
  "L03.10 Celulita membrului superior",
  "M40.04 Cifoza posturala",
  "M81.89 Alte osteoporoze",
  "R57.0 Soc cardiogen",
  "G45.2 Atac ischemic tranzitoriu al teritoriilor arteriale precerebrale multiple si bilaterale",
  "Z95.8 Prezenta altor implante si grefe cardiace si vasculare",
  "I74.8 Embolia si tromboza altor artere",
  "K29.6 Alte gastrite",
  "D44.3 Tumora hipofiza cu evolutie imprevizibila si necunoscuta",
  "M48.95 Spondilopatia",
  "R59.0 Ganglioni limfatici mariti localizati",
  "J42 Bronsita cronica nespecificata",
  "H90.5 Surditate neurosensoriala",
  "I25.10 Cardiopatia aterosclerotica a unor vase nespecificate",
  "R77.0 Anormalitate a albuminei",
  "S36.20 Leziune a pancreasului, parte nespecificata",
  "G30.9 Boala Alzheimer",
  "S09.9 Leziune nespecificata a capului",
  "K50.9 Boala Crohn",
  "E10.8 Diabet mellitus tip 1 cu complicatii nespecificate",
  "I69.8 Sechelele altor boli cerebrovasculare si nespecificate",
  "D73.4 Chistul splinei",
  "C92.00 Leucemia mieloida acuta",
  "M41.23 Alte scolioze idiopatice",
  "J44.8 Alte boli pulmonare obstructive cronice specificate",
  "G92 Encefalopatia toxica",
  "R33 Retentie de urina",
  "B96.2 Escherichia coli [E. coli]",
  "F20.0 Schizofrenia paranoida",
  "I15.9 Hipertensiunea  secundara",
  "I35.2 Stenoza si insuficienta (valva) aortica",
  "N17.2 Insuficienta renala acuta cu necroza medulara",
  "G47.31 Sindromul central al apneei de somn",
  "I82.9 Embolia si tromboza unor vene nespecificate",
  "J44.1 Boala pulmonara obstructiva cronica cu exacerbare acuta",
  "M43.05 Spondiloliza",
  "N25.9 Tulburare care rezulta din deficienta functionarii tubulare renale",
  "D53.1 Alte anemii megaloblastice",
  "E44.0 Malnutritia proteino-energetica moderata",
  "I08.8 Alte boli multiple ale valvelor",
  "J93.9 Pneumotorax",
  "B35.3 Tinea piciorului",
  "G47.30 Apneea de somn",
  "I12.0 Nefropatia hipertensiva cu insuficienta renala",
  "I89.0 Limfedem",
  "K76.8 Alte boli specificate ale ficatului",
  "L03.3 Celulita trunchiului",
  "L30.4 Intertrigo eritematos",
  "M19.99 Artroza",
  "A41.8 Alte tipuri de sepsis specificate",
  "F01.8 Alte forme de dementa vasculara",
  "M10.08 Guta idiopatica",
  "F22.9 Tulburare deliranta persistenta",
  "J34.2 Sept nazal deviat",
  "D44.1 Tumota suprarenala cu evolutie imprevizibila si necunoscuta",
  "Z87.11 Istoric personal de ulcer peptic",
  "E23.2 Diabetul insipid",
  "G70.9 Afectiune neuro-musculara",
  "I63.1 Infarctul cerebral datorita emboliei arterelor precerebrale",
  "R77.9 Anormalitate a proteinei plasmatice",
  "K21.0 Boala refluxului gastro-esofagian cu esofagita",
  "K29.1 Alte gastrite acute",
  "R55 Sincopa si colaps",
  "Z87.8 Istoric personal al altor afectiuni specificate",
  "F70.9 Retardare mentala usoara fara mentionarea deficientei comportamentului",
  "H90.3 Surditate neurosensoriala bilaterala",
  "E04.9 Gusa netoxica",
  "Z82.3 Istoric familial de accident vascular cerebral",
  "C79.5 Tumora maligna secundara a osului si maduvei osoase",
  "M47.25 Alte spondiloze cu radiculopatie",
  "Q89.09 Alte malformatii congenitale specificate ale splinei",
  "T81.0 Hemoragie si hematom complicand o procedura",
  "E01.2 Gusa (endemica) legata de carenta de iod",
  "Z99.8 Dependenta de folosirea altor masini si dispozitive medicale",
  "F00.1* Dementa in boala Alzheimer, cu debut tardiv (G30.1+)",
  "I67.2 Ateroscleroza cerebrala",
  "J17.1* Pneumonia in boli virale clasificate altundeva",
  "M47.82 Alte spondiloze",
  "M51.8 Alte afectiuni specificate ale unui disc intervertebral",
  "G12.2 Bolile neuronului motor",
  "M19.98 Artroza",
  "M25.01 Hemartroza",
  "Z44.8 Amplasarea si ajustarea altor dispozitive prostetice externe",
  "C83.3 Limfom difuz nehodkinian celule mari (difuze)",
  "G03.9 Meningita",
  "M47.85 Alte spondiloze",
  "S72.10 Fractura a sectiunii trohanteriene a femurului",
  "C92.50 Leucemia mielomonocitara acuta",
  "D61.9 Anemia aplazica",
  "C94.50 Mielofibroza acuta",
  "I72.8 Anevrismul altor artere specificate",
  "R16.2 Hepatomegalie si splenomegalie",
  "G47.0 Tulburari de adormire si mentinere a somnului [insomnii]",
  "H40.9 Glaucom",
  "K83.5 Chistul biliar",
  "G46.8* Alte sindroame vasculare cerebrale in bolile cerebro-vasculare (I60-I67+)",
  "I71.4 Anevrismul abdominal",
  "I77.0 Fistula arterio-venoasa, dobindita",
  "R49.0 Disfonie",
  "E78.9 Tulburari de metabolism al lipoproteinelor",
  "I15.1 Hipertensiunea secundara altor afectiuni renale",
  "N04.2 Sindrom nefrotic, glomerulonefrita membranoasa difuza",
  "Q44.6 Boala chistica a ficatului",
  "S22.32 Fractura a unei coaste, alta decat prima coasta",
  "S37.81 Leziune a glandei suprarenale",
  "N02.8 Hematuria persistenta si recurenta, alta",
  "Q61.9 Boala chistica a rinichiului",
  "Z87.0 Istoric personal de boala a aparatului respirator",
  "I67.1 Anevrism cerebral, fara ruptura",
  "C22.0 Carcinom al celulei hepatice",
  "C41.9 Tumora maligna oase si cartilagii",
  "N02.9 Hematuria persistenta si recurenta",
  "A41.0 Sepsis datorit stafilococului auriu",
  "E10.22 Diabet mellitus tip 1 cu nefropatie diabetica stabilita",
  "E10.42 Diabet mellitus tip 1 cu polineuropatie diabetica",
  "Q12.0 Cataracta congenitala",
  "E14.65 Diabet mellitus nespecificat cu control slab",
  "D41.1 Tumora rinichi pelvian cu evolutie imprevizibila si necunoscuta",
  "M47.97 Spondiloza, regiune lombo-sacrala",
  "G45.0 Sindrom vertebro-bazilar",
  "G56.8 Alte mononeuropatii ale membrului superior",
  "I70.1 Ateroscleroza arterei renale",
  "M31.1 Microangiopatia trombotica",
  "M47.20 Alte spondiloze cu radiculopatie",
  "M54.12 Radiculopatia",
  "Q61.8 Alte boli chistice ale rinichiului",
  "D73.1 Hipersplenism",
  "G62.9 Polineuropatia",
  "K70.0 Ciroza alcoolica grasoasa a ficatului",
  "M84.18 Fractura neconsolodata [pseudartroza]",
  "R23.3 Echimoze spontane",
  "I21.9 Infarct miocardic acut",
  "Z90.8 Absenta dobandita a altor organe",
  "N30.8 Alta cistita",
  "M10.97 Guta, glezna si picior",
  "F33.3 Tulburare depresiva recurenta, episod actual sever cu simptome psihotice",
  "Z86.18 Istoric personal al altor boli infectioase si parazitare",
  "Z88.6 Istoric personal de alergie la analgezice",
  "J45.1 Astmul nonalergic",
  "M43.00 Spondiloliza",
  "I32.8* Pericardita in alte boli clasificata altundeva",
  "G62.8 Alte polineuropatii specificate",
  "I65.2 Ocluzia si stenoza arterei carotide",
  "I69.1 Sechelele hemoragiei intracerebrale",
  "N20.2 Litiaza rinichiului cu litiaza ureterului",
  "R47.0 Disfazie si afazie",
  "J15.1 Pneumonia  datorita Pseudomonas",
  "J93.1 Alte forme de pneumotorax spontan",
  "K22.1 Ulcerul esofagului",
  "K92.1 Melena",
  "M54.3 Sciatica",
  "A05.2 Intoxicatia alimentara prin Clostridium perfringens [Clostridium welchii]",
  "M40.19 Alte cifoze secundare",
  "M41.99 Scolioza",
  "S12.0 Fractura a primei vertebre cervicale",
  "S80.0 Contuzie a genunchiului",
  "S82.40 Fractura a fibulei",
  "Z92.2 Istoric personal de utilizare (actuala) pe termen lung a altor medicamente",
  "O87.1 Flebotromboza profunda in timpul lauziei",
  "Z39.1 Ingrijiri si examinari acordate mamei care alapteaza",
  "J15.9 Pneumonia bacteriena",
  "L40.0 Psoriazis vulgaris",
  "M43.06 Spondiloliza",
  "N13.0 Hidronefroza cu obstructia jonctiunii pelviene-ureterale",
  "I77.8 Alte afectiuni specificate ale arterelor si arteriolelor",
  "D38.3 Tumora mediastinului cu evolutie imprevizibila si necunoscuta",
  "H90.6 Surditate bilaterala mixta de transmisie si neurosensoriala",
  "G25.1 Tremuraturi provocate medicamentos",
  "G31.8 Alte afectiuni degenerative specificate ale sistemului nervos",
  "G91.9 Hidrocefalia",
  "H81.8 Alte afectiuni ale functiei vestibulare",
  "I63.2 Infarctul cerebral datorita ocluziei sau stenozei nespecificate ale arterelor precerebrale",
  "F70.8 Retardare mentala usoara, alte deficiente ale comportamentului",
  "K71.2 Boala toxica a ficatului cu hepatita acuta",
  "M81.00 Osteoporoza postmenopauza",
  "N30.9 Cistita",
  "A16.1 Tubercoloza pulmonara, fara investigatii bacteriologice sau histologice",
  "D45 Policitemia esentiala",
  "Z85.8 Istoric personal de tumori maligne ale altor organe si sisteme",
  "E21.0 Hiperparatiroidism primar",
  "H81.1 Vertij paroxistic benign",
  "M48.02 Stenoza canalului medular",
  "M81.90 Osteoporoza",
  "R21 Rash si alte eruptii nespecificate ale pielii",
  "R42 Ameteala si vertij",
  "Z96.64 Prezenta unui implant de sold",
  "I45.6 Sindrom de pre-excitatie",
  "Z90.4 Absenta dobandita a altor parti ale aparatului digestiv",
  "K76.6 Hipertensiunea portala",
  "I95.1 Hipotensiunea ortostatica",
  "M43.02 Spondiloliza",
  "E77.8 Alte tulburari de metabolism al glicoproteinelor",
  "J15.8 Alte pneumonii bacteriene",
  "K63.2 Fistula intestinului",
  "K86.8 Alte boli specificate ale pancreasului",
  "M41.85 Alte forme de scolioza",
  "T81.41 Infectie a plagii ca urmare a unei proceduri",
  "Z43.3 Supravegherea colostomiei",
  "D69.3 Purpura trombopenica idiopatica",
  "N01.0 Sindrom nefritic progresiv rapid, anomalie glomerulara minora",
  "N04.9 Sindrol nefrotic",
  "R60.1 Edem generalizat",
  "E11.72 Diabet mellitus tip 2 cu caracteristici de rezistenta la insulina",
  "G31.0 Atrofia cerebrala circumscrisa",
  "M62.38 Sindromul de imobilitate (paraplegica)",
  "M80.86 Alte osteoporoze cu fractura patologica",
  "E14.23 Diabet mellitus nespecificat cu boala renala stadiu final [ESRD]",
  "G40.80 Alte epilepsii",
  "I84.2 Hemoroizi interni fara complicatii",
  "K40.21 Hernia inghinala bilaterala, recidivanta",
  "K92.9 Boala sistemului digestiv",
  "Z87.10 Istoric personal de boala digestiva nespecificata",
  "D38.1 Tumora traheii, bronhiilor si pulmonului cu evolutie imprevizibila si necunoscuta",
  "D40.0 Tumora prostata cu evolutie imprevizibila si necunoscuta",
  "H26.9 Cataracta",
  "E85.8 Alte amiloidoze",
  "I42.9 Cardiomiopatia",
  "Z46.9 Amplasarea si ajustarea unui dispozitiv nespecificat",
  "I44.2 Bloc atrio-ventricular complet",
  "I44.3 Alte blocuri atrio-ventriculare si nespecificate",
  "M81.80 Alte osteoporoze",
  "Z94.0 Starea transplantului de rinichi",
  "D51.0 Anemia prin carenta de vitamina B12, datorita carentei unui factor intrinsec",
  "E11.01 Diabet mellitus tip 2 cu hiperosmolaritate fara coma noncetotica hiperglicemica-hiperosmolara [NKHHC]",
  "H25.9 Cataracta senila",
  "F02.3* Dementa in boala Parkinson (G20+)",
  "K25.7 Ulcerul gastric",
  "C79.88 Tumora maligna secundara cu alte localizari specificate",
  "Z80.5 Istoric familial de tumora maligna a tractului urinar",
  "E75.5 Alte tulburari ale lipidelor de rezerva",
  "H81.3 Alte vertijuri periferice",
  "M48.46 Fractura vertebrala de oboseala",
  "N43.2 Alt hidrocel",
  "E87.8 Alte tulburari hidrice si electrolitice",
  "I95.0 Hipotensiunea idiopatica",
  "I45.9 Tulburari de conducere",
  "J06.9 Infectii acute ale cailor respiratorii superioare",
  "M41.54 Alta scolioza secundara",
  "M41.56 Alta scolioza secundara",
  "M48.25 Artroza interspinoasa",
  "J15.2 Pneumonia datorira stafilococilor",
  "J94.8 Alte afectiuni pleurale specificate",
  "N62 Hipertrofia sanului",
  "X69 Auto-otravire intentionata prin si la expunerea la alte substante chimice si nocive nespecificate",
  "F30.9 Episod maniacal nespecificat",
  "N01.7 Sindrom nefritic progresiv rapid, glomerulonefrita difuza in crestere",
  "Z45.2 Ajustarea si intretinerea unui dispozitiv de acces vascular",
  "E83.0 Tulburari de metabolism al cuprului",
  "M43.90 Dorsopatia deformanta",
  "L02.2 Abces cutanat, furuncul si furuncul antracoid al trunchiului",
  "E11.40 Diabet mellitus tip 2 cu neuropatie nespecificata",
  "J93.8 Alte forme de pneumotorax",
  "N21.9 Litiaza [calcul] cailor urinare inferioare",
  "D44.0 Tumora tiroida cu evolutie imprevizibila si necunoscuta",
  "F00.9* Dementa in boala Alzheimer, nespecificata (G30.9+)",
  "G40.91 Epilepsia, cu epilepsie intractabila",
  "D69.1 Defecte calitative ale trombocitelor",
  "I63.0 Infarctul cerebral datorita trombozei arterelor precerebrale",
  "S72.11 Fractura a sectiunii intertrohanteriene a femurului",
  "B09 Infectii virale caracterizate prin leziuni cutaneo-mucoase",
  "D22.5 Nev cu melanocisti al trunchiului",
  "E11.21 Diabet mellitus tip 2 cu nefropatie diabetica incipienta",
  "G81.9 Hemiplegia",
  "I66.9 Ocluzia si stenoza arterelor cerebrale nespecificate",
  "H35.3 Degenerescenta maculei si polului posterior",
  "H93.2 Alte perceptii de auz anormale",
  "I37.1 Insuficienta valvei pulmonare",
  "K91.5 Sindromul de postcolecistectomie",
  "E11.12 Diabet mellitus tip 2 cu acidocetoza, cu coma",
  "J98.2 Emfizem interstitial",
  "T88.4 Intubare esuata sau dificila",
  "D13.4 Tumora benigna ficat",
  "I05.1 Insuficienta mitrala, reumatismala",
  "T78.9 Efect advers",
  "K80.80 Alte colelitiaze, fara mentionarea obstructiei",
  "D51.9 Anemii prin carenta de vitamina B12",
  "E13.21 Alte forme specificate de diabet mellitus cu nefropatie diabetica incipienta",
  "N13.1 Hidronefroza cu strictura ureterala",
  "N28.8 Alte tulburari specificate ale rinichiului si ureterului",
  "T83.5 Infectie si reactie inflamatorie datorita unui dispozitiv prostetic, implant si grefa a sistemuluii urinar",
  "Z51.3 Transfuzie de sange fara un diagnostic stabilit",
  "M13.11 Monoartrita",
  "G82.10 Paraplegia spastica",
  "G90.2 Sindromul Horner",
  "I65.0 Ocluzia si stenoza arterei vertebrale",
  "Z96.1 Prezenta lentilelor intraoculare",
  "G54.0 Afectiunile plexului brahial",
  "M40.24 Alte cifoze si nespecificate",
  "M47.83 Alte spondiloze",
  "M53.88 Alte dorsopatii specificate, regiune sacrala si sacro-coccigiana",
  "D17.1 Tumora lipomatoasa benigna a pielii si a tesutului subcutanat al trunchiului",
  "F60.4 Tulburare de personalitate histrionica",
  "F61 Tulburari mixte de personalitate si altele",
  "I83.2 Vene varicoase ale extremitatilor inferioare cu ulceratie si inflamatie",
  "E13.9 Alte forme specificate de diabet mellitus fara complicatii",
  "A08.5 Alte infectii intestinale specificate",
  "B37.88 Candidiaza cu alte localizari",
  "J94.9 Afectiune pleurala",
  "M46.85 Alte spondilopatii inflamatorii specificate",
  "I61.4 Hemoragia intracerebrala in cerebel",
  "M43.09 Spondiloliza",
  "S20.2 Contuzie a toracelui",
  "G93.8 Alte afectiuni specificate ale creierului",
  "I33.0 Endocardita acuta si subacuta infectioasa",
  "M13.0 Poliartrita",
  "I21.2 Infarct miocardic acut transmural cu alte localizari",
  "T86.1 Esec si respingere a unui transplant de rinichi",
  "F60.9 Tulburare de personalitate",
  "Z72.0 Folosirea tutunului, in prezent",
  "Z73.6 Limitarea activitatii datorita invaliditatii",
  "D86.0 Sarcoidoza plamanului",
  "F00.2* Dementa in boala Alzheimer, forma atipica sau mixta (G30.8+)",
  "F05.1 Delir supra-adaugat unei demente",
  "R32 Incontinenta urinara nespecificata",
  "R91 Rezultate anormale in diagnosticul imagistic al plamanului",
  "I26.0 Embolia vaselor pulmonare cu mentiunea cordului pulmonar acut",
  "K92.2 Hemoragia gastro-intestinala",
  "R06.8 Alte anomaliile de respiratie si nespecificate",
  "D68.9 Anomalia de coagulare",
  "K52.8 Alte gastroenterite si colite neinfectioase specificate",
  "T13.6 Amputatie traumatica a membrului inferior, nivel nespecificat",
  "D14.4 Tumora benigna aparat respirator",
  "E13.22 Alte forme specificate de diabet mellitus cu nefropatie diabetica stabilita",
  "E13.42 Alte forme specificate de diabet mellitus cu polineuropatie diabetica",
  "K80.10 Calcul al vezicii biliare cu o alta forma de colecistita",
  "L80 Vitiligo",
  "R57.9 Soc",
  "R16.0 Hepatomegalie",
  "J43.2 Emfizem centrolobular",
  "C44.3 Tumora maligna pielea fetei, alte localizari si neprecizate",
  "E89.0 Hipotiroidism postprocedural",
  "M79.88 Alte afectiuni specificate ale tesuturilor moi",
  "Z91.0 Istoric personal de alergie, alta decit cea la medicamente si substante biologice",
  "M45.09 Spondilita anchilozanta",
  "C54.1 Tumora maligna endometru",
  "K45.8 Alte hernii abdominale specificate fara obstructie sau gangrena",
  "L21.9 Dermatita seboreica",
  "Z90.3 Absenta dobandita a unei parti a stomacului",
  "I42.2 Alte cardiomiopatii hipertrofice",
  "I74.0 Embolia si tromboza aortei abdominale",
  "Z98.8 Alte stari postprocedurale specificate",
  "B37.3+ Candidiaza vulvei si vaginului (M77.1*)",
  "G91.8 Alte hidrocefalii",
  "S06.28 Alta leziune difuza cerebrala si cerebeloasa",
  "M19.01 Artroza primara a altor articulatii",
  "A41.1 Sepsis datorit altor stafilococi, specificati",
  "I77.6 Arterita",
  "D73.5 Infarctul splinei",
  "I74.5 Embolia si tromboza arterei iliace",
  "N28.0 Ischemia si infarctul rinichiului",
  "M06.09 Artrita reumatoida seronegativa",
  "I80.3 Flebita si tromboflebita extremitatilor inferioare",
  "N01.1 Sindrom nefritic progresiv rapid, leziuni glomerulare segmentare si focale",
  "M41.24 Alte scolioze idiopatice",
  "Q61.41 Displazia renala chistica, unilaterala",
  "E79.9 Tulburari de metabolism al purinelor si pirimidinei",
  "D48.0 Tumora os si cartilagiu articular cu evolutie imprevizibila si necunoscuta",
  "G51.0 Paralizia Bell",
  "D37.1 Tumora stomacului  cu evolutie imprevizibila si necunoscuta",
  "F43.2 Tulburare de adaptare",
  "E04.0 Gusa difuza netoxica",
  "I71.2 Anevrismul toracic",
  "I72.3 Anevrismul arterei iliace",
  "I47.0 Aritmia ventriculara de reintrare",
  "L50.9 Urticaria",
  "Z46.8 Amplasarea si ajustarea altor dispozitive specificate",
  "E01.1 Gusa multinodulara (endemica) legata de o carenta de iod",
  "E06.9 Tiroidita",
  "K57.92 Diverticulita intestinului, fara perforatie si abces, fara mentionarea hemoragiei",
  "N11.0 Pielonefrita neobstructiva cronica asociata cu un reflux",
  "S22.41 Fracturi multiple de coaste, implicand prima coasta",
  "E11.33 Diabet mellitus tip 2 cu retinopatie proliferativa",
  "M81.98 Osteoporoza",
  "M45.06 Spondilita anchilozanta",
  "E83.9 Tulburari de metabolism al mineralelor",
  "S22.00 Fractura de vertebre toracice",
  "N60.2 Adenofibroza sanului",
  "Q21.1 Defect septal atrial",
  "I69.2 Sechelele altor hemoragii intracraniene netraumatice",
  "I97.2 Sindromul limfedemului dupa mastectomie",
  "M84.35 Fractura prin solicitare excesiva, regiune pelviana si coapsa",
  "H81.4 Vertijul de origine centrala",
  "N30.0 Cistita acuta",
  "M35.3 Polimialgia reumatismala",
  "M51.2 Alta deplasarea a unui alt disc intervertebral specificat",
  "M84.40 Fractura patologica",
  "D64.1 Anemia sideroblastica secundara datorita unei boli",
  "Q61.2 Rinichi polichistic, autosomal dominant",
  "B37.81 Esofagita prin Candida",
  "D41.4 Tumora vezica urinara cu evolutie imprevizibila si necunoscuta",
  "Z12.6 Examinare speciala de screening pentru tumora vezicii urinare",
  "H91.1 Presbiacuzia",
  "H34.9 Ocluzie vasculara retiniana",
  "Z88.4 Istoric personal de alergie la anestezice",
  "I05.8 Alte boli ale valvei mitrale",
  "R00.8 Alte anomalii de ritm cardiac si nespecificate",
  "I31.9 Boala pericardului",
  "G93.6 Edem cerebral",
  "K72.0 Insuficienta hepatica acuta si subacuta",
  "T81.8 Alte complicatii ale procedurilor",
  "C44.5 Tumora maligna pielea trunchiului",
  "G40.40 Alte epilepsii generalizate si sindroame epileptice, fara epilepsia intractabila",
  "M06.91 Artrita reumatoida",
  "U07.2 COVID-19 cu virus neidentificat",
  "E05.8 Alte tireotoxicoze",
  "T96 Sechele ale intoxicatiilor prin droguri",
  "M67.40 Ganglion",
  "D16.0 Tumora benigna omoplat si oase lungi ale membrului superior",
  "K13.0 Bolile buzelor",
  "K91.1 Sindroame dupa chirurgia gastrica",
  "Y83.2 Interventie chirurgicala cu anastomoza, bypass sau grefa",
  "D39.0 Tumora uter cu evolutie imprevizibila si necunoscuta",
  "J01.4 Pansinuzita acuta",
  "K26.9 Ulcerul duodenal nespecificat ca acut sau cronic",
  "C78.6 Tumora maligna secundara a retroperitoneului si peritoneului",
  "Z46.6 Amplasarea si ajustarea unei proteze urinare",
  "D46.9 Sindrom mielodisplazic",
  "C34.8 Tumora maligna leziune depasind bronhiile si pulmonul",
  "I25.3 Anevrismul inimii",
  "M19.88 Alte artroze specificate",
  "S36.08 Alta leziune a splinei",
  "S72.00 Fractura a colului femural",
  "I70.20 Ateroscleroza arterelor extremitatilor",
  "N42.9 Tulburare a prostatei",
  "L42 Pitiriazis rozeu Gilbert",
  "N51.0* Afectiuni ale prostatei in boli clasificate altundeva",
  "Q61.50 Rinichi chistic medular",
  "H90.1 Surditate unilaterala de transmisie, fara alterarea auditiei celeilalte urechi",
  "I30.8 Alte forme de pericardita acuta",
  "I44.6 Alte blocuri fasciculare si nespecificate",
  "K86.3 Pseudochistul pancreasului",
  "G91.0 Hidrocefalia comunicanta",
  "H54.2 Scaderea vederii ambilor ochi",
  "I67.9 Boala cerebrovasculara",
  "M62.82 Alte afectiuni specificate ale muschiului",
  "C34.3 Tumora maligna lobul inferior ",
  "D18.04 Hemangiom, structuri ale sistemului digestiv",
  "R64 Casexie",
  "F43.0 Reactie acuta la stress",
  "F33.4 Tulburare depresiva recurenta, in remisie in prezent",
  "F20.9 Schizofrenia",
  "E78.6 Deficit in lipoproteine",
  "N04.8 Sindrom nefrotic, altul",
  "A41.2 Sepsis datorit unui stafilococ nespecificat",
  "I86.8 Vene varicoase cu alte localizari specificate",
  "N13.9 Uropatia cu reflux si obstructiva",
  "N32.3 Diverticulul vezicii urinare",
  "M53.27 Instabilitati ale coloanei vertebrale",
  "C91.90 Leucemia limfoida",
  "D01.7 Carcinom in situ alte organe digistive precizate",
  "D17.5 Tumora lipomatoasa benigna a organelor intraabdominale",
  "K31.7 Polip al stomacului si duodenului",
  "C50.5 Tumora maligna cadranul infero-extern al sanului",
  "Z40.00 Chirurgie profilactica pentru factori de risc legati de tumorile maligne, san",
  "M19.08 Artroza primara a altor articulatii",
  "D70 Agranulocitoza",
  "I61.2 Hemoragia intracerebrala in emisfere",
  "K74.1 Scleroza hepatica",
  "M16.1 Alte coxartroze primare",
  "M48.20 Artroza interspinoasa",
  "E16.9 Tulburari ale secretiei interne pancreatice",
  "E73.9 Intoleranta la lactoza",
  "H90.2 Surditate de transmisie",
  "K80.50 Calculul canalelor biliare fara angiocolita si colecistita",
  "M15.9 Poliartroza",
  "M54.5 Dorsalgie joasa",
  "S27.38 Alte leziuni si nespecificate ale plamanului",
  "M81.09 Osteoporoza postmenopauza",
  "B99 Boli infectioase, alte si nespecificate",
  "E88.8 Alte tulburari de metabolism specificate",
  "I47.9 Tahicardia paroxistica",
  "I72.2 Anevrismul arterei renale",
  "K46.9 Hernia abdominala nespecificata fara obstructie sau gangrena",
  "M80.01 Osteoporoza postmenopauza cu fractura patologica",
  "M89.09 Algoneurodistrofia",
  "D09.0 Carcinom in situ vezica urinara",
  "I81 Tromboza venei porte",
  "I85.0 Varice esofagiene cu sangerare",
  "I86.4 Varice gastrice",
  "K70.3 Ciroza alcoolica a ficatului",
  "K76.7 Sindromul hepato-renal",
  "M40.02 Cifoza posturala",
  "C16.2 Tumora maligna corpul stomacului",
  "J32.3 Sinuzita sfenoidala cronica",
  "M50.1 Afectiune a discului cervical cu radiculopatie",
  "C18.9 Tumora maligna colon ",
  "L40.5+ Artropatia psoriazica (M07.0-M07.3*, M09.0*)",
  "L40.8 Alte forme de psoriazis",
  "M07.30* Alte artropatii psoriazice, localizari multiple (L40.5+)",
  "M53.90 Dorsopatia",
  "A41.4 Sepsis datorit anaerobilor",
  "E88.2 Lipomatoza",
  "M41.86 Alte forme de scolioza",
  "K57.02 Diverticulita intestinului subtire cu perforatie si abces",
  "N95.0 Sangerari postmenopauza",
  "K44.0 Hernia diafragmatica cu obstructie, fara gangrena",
  "J45.8 Astmul asociat",
  "M13.95 Artrita",
  "M47.86 Alte spondiloze",
  "S22.44 Fracturi multiple de coaste implicand patru sau mai multe coaste",
  "F20.3 Schizofrenie nediferentiata",
  "E11.52 Diabet mellitus tip 2 cu angiopatie periferica",
  "D04.7 Carcinom in situ pielea membrului inferior, inclusiv soldul",
  "Z22.59 Purtator de alte forme de hepatita virala specificate",
  "M79.28 Nevralgia si nevrita",
  "Q76.0 Spina bifida occulta",
  "M40.09 Cifoza posturala",
  "M41.89 Alte forme de scolioza",
  "N99.9 Afectiune postprocedurala a sistemului genito-urinar",
  "M10.34 Guta datorita deficientei functiei renale, mana",
  "M10.37 Guta datorita deficientei functiei renale, lezna si picior",
  "K82.4 Colesteroloza vezicii biliare",
  "Q40.1 Hernia hiatala congenitala",
  "E11.13 Diabet mellitus tip 2 cu acidoza lactica, fara coma",
  "R68.0 Hipotermia, neasociata cu temperatura scazuta a mediului inconjurator",
  "C85.1 Limfoame cu celule B",
  "M86.96 Osteomielita",
  "Q76.5 Coasta cervicala",
  "M54.90 Dorsalgia",
  "Y83.6 Ablatia unui alt organ (partiala) (totala)",
  "Z90.0 Absenta dobandita a unei parti a capului si gatului",
  "B00.1 Dermita veziculara datorita virusului herpetic",
  "K71.1 Boala toxica a ficatului cu necroza hepatica",
  "M63.85* Alte afectiuni ale muschilor in boli clasificate altundeva",
  "D14.3 Tumora benigna bronhii si pulmon",
  "I21.1 Infarct miocardic acut transmural al peretului inferior",
  "M15.3 Artroza secundara multipla",
  "D59.9 Anemii hemolitice dobandite",
  "E78.8 Alte tulburari de metabolism al lipoproteinelor",
  "N35.9 Strictura uretrala",
  "J81 Edem pulmonar",
  "E67.8 Alte excese de aport specificate",
  "I15.0 Hipertensiunea renovasculara",
  "M40.05 Cifoza posturala",
  "I87.0 Sindromul postflebitic",
  "I73.0 Sindromul Raynaud",
  "L72.0 Chist epidermic",
  "B00.2 Gingivo-stomatita si faringo-amigdalita cu virusul herpetic",
  "N35.8 Alta strictura uretrala",
  "F10.3 Tulburari mentale si de comportament datorite folosirii alcoolului, sindromul de sevraj",
  "F17.3 Tulburari mentale si de comportament datorite folosirii tutunului",
  "M82.80* Osteoporoza in alte boli clasificate altundeva",
  "T92.1 Sechele ale fracturii bratului",
  "T93.2 Sechele ale altor fracturi ale membrului inferior",
  "Z74.8 Alte probleme legate de dependenta fata de persoana care asigura ingrijiri medicale",
  "Z98.0 Starea bypassului intestinal si anastomozei",
  "C06.9 Tumora maligna gura",
  "I61.0 Hemoragia intracerebrala in emisfere, subcorticala",
  "Z86.41 Istoric personal de tulburare datorita consumului de alcool",
  "E06.5 Alte tiroidite cronice",
  "C15.9 Tumora maligna esofagul ",
  "I35.8 Alte afectiuni ale valvei aortice",
  "Z51.2 Alte forme de chimioterapie",
  "E07.9 Afectiunea tiroidei",
  "C78.2 Tumora maligna secundara a pleurei",
  "B37.4+ Candidiaza altor localizari uro-genitale",
  "K73.9 Hepatita cronica",
  "Z71.6 Consiliere si supraveghere a tulburarilor datorite consumului de tutun",
  "B37.1 Candidiaza pulmonara",
  "C96.7 Alte tumori maligne precizate ale tesutului limfoid, hematopoietic si inrudite",
  "J43.1 Emfizem panlobular",
  "J98.1 Colaps pulmonar",
  "I22.8 Infarct miocardic ulterior cu alte localizari specificate",
  "I25.13 Cardiopatia aterosclerotica a unei grefe de bypass nonautolog",
  "B44.0 Aspergilloza pulmonara invaziva",
  "I80.8 Flebita si tromboflebita cu alte localizari",
  "Q44.5 Alte malformatii congenitale ale cailor biliare",
  "D42.0 Tumora meninge cerebral cu evolutie imprevizibila si necunoscuta",
  "Q63.89 Alte malformatii congenitale ale rinichiului specificate",
  "M16.6 Alte coxartroze secundare, bilaterale",
  "M54.16 Radiculopatia",
  "A41.58 Sepsis datorit altor organisme Gram-negative",
  "J15.0 Pneumonia datorita Klebsiella pneumoniae",
  "K38.9 Boala apendicelui",
  "F71.8 Retardare mentala moderata alte deficiente ale comportamentului",
  "M05.30+ Artrita reumatoida cu implicarea altor organe sau sisteme",
  "F10.2 Tulburari mentale si de comportament datorite folosirii alcoolului, sindromul de dependenta",
  "C71.9 Tumora maligna creierul",
  "E11.71 Diabet mellitus tip 2 cu complicatii microvasculare multiple",
  "Z94.1 Starea transplantului de inima",
  "B96.5 Pseudomonas, (aeruginosa) (Burkholderia pseudommallei) (mallei) cauza unor boli clasate la alte capitole",
  "I84.8 Hemoroizi nespecificati cu alte complicatii",
  "K29.4 Gastrita atrofica cronica",
  "K57.31 Diverticuloza intestinului gros fara perforatie sau abces, cu hemoragie",
  "H06.2* Exoftalmia tireotoxica (E05.-+)",
  "S22.06 Fractura de vertebre toracice, nivelul T11 si T12",
  "I61.9 Hemoragia intracerebrala",
  "I44.1 Bloc atrio-ventricular, gradul doi",
  "E43 Malnutritia proteino-energetica grava",
  "K71.7 Boala toxica a ficatului cu fibroza si ciroza ficatului",
  "I71.01 Disectia aortei toracice",
  "M81.58 Osteoporoza idiopatica",
  "T91.1 Sechele ale fracturii coloanei vertebrale",
  "C43.7 Melanom malign al membrelor inferioare",
  "I68.2* Arterita cerebrala in alte boli clasificate altundeva",
  "I99 Alte afectiuni ale sistemului circulator si nespecificate",
  "E83.1 Tulburari de metabolism al fierului",
  "F06.4 Tulburari anxioase organice",
  "C45.9 Mesoteliom, fara precizari",
  "K51.0 Enterocolita (cronica) ulceroasa",
  "Q89.19 Alte malformatii congenitale specificate ale glandei suprarenale",
  "Y83.1 Interventie chirurgicala cu implant al unui dispozitiv intern artificial",
  "Y83.4 Alte interventii chirurgicale de reconstructie",
  "J30.4 Rinita alergica",
  "Z80.8 Istoric familial de tumora maligna a altor organe si sisteme",
  "J13 Pneumonia datorita Streptococcus pneumoniae",
  "D48.9 Tumora cu evolutie imprevizibila si necunoscuta",
  "J34.8 Alte boli specificate ale nasului si sinusului nazal",
  "M62.80 Alte afectiuni specificate ale muschiului",
  "G80.00 Paralizia cerebrala spastica",
  "D35.2 Tumora benigna hipofiza",
  "F31.3 Tulburare afectiva bipolara, episod actual de depresie usoara sau medie",
  "I34.9 Afectiunea nereumatismala a valvulei mitrale",
  "I30.1 Pericardita infectioasa",
  "D00.0 Carcinom in situ buza, cavitate bucala si faringe",
  "F13.3 Tulburari mentale si de comportament datorite folosirii sedativelor sau hipnoticelor",
  "N41.1 Prostatita cronica",
  "I06.0 Stenoza aortica reumatismala",
  "I21.4 Infarct miocardic acut subendocardic",
  "Z71.4 Consiliere si supraveghere a tulburarilor datorite consumului de alcool",
  "E71.3 Tulburari de metabolism al acizilor grasi",
  "Q61.0 Chist renal unic congenital",
  "B00.4 Encefalita  cu virusul herpetic",
  "M41.20 Alte scolioze idiopatice",
  "M48.53 Prabusire vertebrala",
  "D47.1 Boala mieloproliferativa cronica",
  "L23.4 Dermatita alergica de contact datorita vopselelor",
  "C91.10 Leucemia limfoida cronica",
  "D46.0 Anemie refractara fara sideroblasti, astfel declarata",
  "F33.8 Alte tulburari depresive recurente",
  "M85.45 Chist osos solitar",
  "N14.2 Nefropatia cauzata de un drog, medicament, sau substanta bilogica nespecificate",
  "M48.44 Fractura vertebrala de oboseala",
  "M53.96 Dorsopatia",
  "G11.2 Ataxia cerebeloasa tardiva",
  "G23.2 Degenerescenta striato-nigrica [nigrostriate]",
  "M48.54 Prabusire vertebrala",
  "M90.88* Osteopatia in alte boli clasificate altundeva",
  "H50.9 Strabism",
  "C53.9 Tumora maligna col uterin",
  "E80.4 Sindromul Gilbert",
  "E09.9 Reglementarea intolerantei la glucoza fara complicatii",
  "M40.03 Cifoza posturala",
  "I71.02 Disectia aortei abdominale",
  "K29.8 Duodenita",
  "T88.6 Soc anafilactic datorit efectelor adverse ale unui drog sau medicament corect administrat",
  "E74.8 Alte tulburari specificate de metabolism al carbohidratilor",
  "Q60.0 Agenezia renala unilaterala",
  "T79.2 Hemoragie traumatica secundara si recurenta",
  "I79.0* Anevrismul aortei in boli clasificate altundeva",
  "T81.42 Sepsis ca urmare a unei proceduri",
  "G82.22 Paraplegia, cronica",
  "L97 Ulceratia membrului inferior",
  "D43.2 Tumora creier, fara precizare cu evolutie imprevizibila si necunoscuta",
  "I65.1 Ocluzia si stenoza arterei bazilare",
  "J30.3 Alte rinite alergice",
  "E53.8 Carenta de alte vitamine din grupa B",
  "S02.2 Fractura a oaselor nasale",
  "A41.50 Sepsis datorit organismelor Gram-negative nespecificate",
  "G21.8 Alte parkinsonisme secundare",
  "G83.8 Alte sindroame paralitice specificate",
  "I77.9 Afectiuni ale arterelor si arteriolelor",
  "M62.24 Infarctul ischemic muscular",
  "S35.2 Leziune a arterelor celiace sau mezenterice",
  "E74.9 Tulburari de metabolism al carbohidratilor",
  "M11.28 Alte condrocalcinoze",
  "M41.96 Scolioza",
  "E27.8 Alte tulburari specificate ale glandei adrenale",
  "M41.55 Alta scolioza secundara",
  "D30.3 Tumora benigna vezica urinara",
  "G82.46 Tetraplegia spastica, incompleta",
  "H50.0 Strabism convergent concomitent",
  "D61.1 Anemia aplazica provocata de medicamente",
  "N99.3 Prolaps al peretelui vaginal dupa histerectomie",
  "K72.9 Insuficienta hepatica",
  "S25.0 Leziune a aortei toracice",
  "I42.8 Alte  cardiomiopatii",
  "D12.8 Tumora benigna rect",
  "K57.50 Diverticuloza atat a intestinului gros cat si a intestinului subtire fara perforatie si abces",
  "D38.4 Tumora timusului cu evolutie imprevizibila si necunoscuta",
  "E05.0 Tireotoxicoza cu gusa difuza",
  "M43.03 Spondiloliza",
  "K29.9 Gastro-duodenita",
  "L26 Dermatita exfoliativa",
  "M62.89 Alte afectiuni specificate ale muschiului",
  "K63.3 Ulcer al intestinului",
  "K56.5 Aderente intestinale [bride] cu obstructie",
  "R45.2 Nefericire",
  "R45.5 Ostilitate",
  "D72.9 Anomalia celulelor albe",
  "D75.8 Alte boli specificate ale sangelui si ale organelor hematopoietice",
  "E16.1 Alte hipoglicemii",
  "D32.0 Tumora benigna meninge cerebral",
  "S06.20 Leziune difuza cerebrala si cerebeloasa",
  "D30.0 Tumora benigna rinichi",
  "H49.0 Paralizia celui de-al treilea nerv [oculomotor]",
  "T23.2 Arsura a pumnului si mainii cu adancime partiala [flictene, pierdere epidermala]",
  "F17.2 Tulburari mentale si de comportament datorite folosirii tutunului",
  "D69.9 Afectiuni hemoragice",
  "K80.00 Calcul al vezicii biliare cu colecistita acuta",
  "F22.0 Tulburare deliranta",
  "H81.9 Afectiunea functiei vestibulare",
  "T94.1 Sechele ale leziunilor traumatice",
  "R17 Icter",
  "C11.9 Tumora maligna rinofaringe ",
  "M54.85 Alte dorsalgii",
  "Z93.3 Starea colostomiei",
  "F05.8 Alte forme de delir",
  "M79.85 Alte afectiuni specificate ale tesuturilor moi",
  "I60.9 Hemoragia subarahnoida",
  "M41.39 Scolioza prin anomalie toracica",
  "Q78.4 Encondromatoza",
  "H90.8 Surditate mixta de transmisie si neurosensoriala",
  "M05.84 Alte artrite reumatoide seropozitive",
  "M62.26 Infarctul ischemic muscular",
  "Z96.65 Prezenta unui implant de genunchi",
  "J32.9 Sinuzita cronica",
  "C20 Tumora maligna a rectului",
  "K62.7 Proctita datorita iradierii",
  "I34.1 Prolapsul (valva) mitral",
  "Z54.2 Convalescenta dupa chimioterapie",
  "Z92.3 Istoric personal de iradiere",
  "M08.18 Spondilita anchilozanta juvenila",
  "Z86.43 Istoric personal de tulburare datorita consumului de tutun",
  "K75.0 Abces al ficatului",
  "Z48.0 Supravegherea suturilor si pansamentelor chirurgicale",
  "Z48.8 Alte ingrijiri de control specificate dupa o interventie chirurgicala",
  "Z54.0 Convalescenta dupa interventie chirurgicala",
  "H40.1 Glaucom primar in unghi deschis",
  "C18.6 Tumora maligna colonul descendent",
  "C25.4 Tumora maligna pancreas endrocrin",
  "C55 Tumora maligna a uterului, localizare neprecizata",
  "C57.4 Tumora maligna anexele uterului",
  "K36 Alte forme de apendicita",
  "N03.9 Sindrom nefritic cronic",
  "I95.8 Alte hipotensiuni",
  "M19.91 Artroza",
  "M41.26 Alte scolioze idiopatice",
  "M79.22 Nevralgia si nevrita",
  "E83.8 Alte tulburari de metabolism al mineralelor",
  "K57.90 Diverticuloza intestinului",
  "M54.6 Rahialgie toracica",
  "K44.1 Hernia diafragmatica cu gangrena",
  "S37.01 Contuzie si hematom ale rinichiului",
  "K05.5 Alte boli periodontale",
  "M48.96 Spondilopatia",
  "N93.8 Alte sangerari anormale specificate ale uterului si vaginului",
  "S00.81 Leziune superficiala a altor parti ale capului, abraziune",
  "M23.29 Leziunea meniscului datorita unei rupturi sau leziuni vechi, ligament nespecificat sau menisc nespecificat",
  "J39.2 Alte boli ale faringelui",
  "M42.13 Osteocondroza vertebrala a adultului",
  "M85.39 Osteita condensata",
  "M85.48 Chist osos solitar",
  "I63.5 Infarctul cerebral datorita ocluziei sau stenozei nespecificate ale arterelor cerebrale",
  "J16.8 Pneumonia datorita altor microorganisme infectioase specificate",
  "C43.9 Melanomul malign al pielii",
  "D04.9 Carcinom in situ piele",
  "K51.8 Alte colite ulcerative",
  "I33.9 Endocardita acuta",
  "D23.9 Tumora benigna pielea",
  "L30.8 Alte dermatite specificate",
  "S43.00 Luxatie a umarului",
  "S82.21 Fractura a diafizei tibiei cu fractura fibulei (orice parte)",
  "D42.9 Tumora meninge cu evolutie imprevizibila si necunoscuta",
  "D48.6 Tumora sin cu evolutie imprevizibila si necunoscuta",
  "R71 Anormalitate a globulelor rosii",
  "D51.2 Carenta de transcobalamina II",
  "K93.8* Afectiunile altor organe digestive specificate in boli clasificate altundeva",
  "R39.1 Alte dificultati de mictiune",
  "S06.34 Hematom cerebelos in focar",
  "I45.8 Alte tulburari de conducere specificate",
  "E63.9 Carenta nutritionala",
  "D37.6 Tumora ficatului si cailor biliare cu evolutie imprevizibila si necunoscuta",
  "L03.11 Celulita membrului inferior",
  "S33.2 Luxatie a articulatiei sacroiliace si sacrococcigiene",
  "G46.4* Sindrom cerebelos vascular (I60-I67+)",
  "I28.8 Alte boli specificate ale vaselor pulmonare",
  "K45.0 Alte hernii abdominale specificate cu obstructie",
  "N84.0 Polip al corpului uterin",
  "N85.0 Hiperplazia glandulara a endometrului",
  "Z86.3 Istoric personal de boli endocrine, de nutritie si metabolism",
  "Q87.81 Sindromul Alport",
  "J10.0 Gripa cu pneumonie, virus gripal identificat",
  "M15.0 (Osteo)artroza primara generalizata",
  "I60.7 Hemoragia subarahnoida de la artere intracraniene",
  "M76.9 Entezopatia membrului inferior",
  "S06.33 Hematom cerebral in focar",
  "W19 Cadere nespecificata",
  "N92.0 Menstruatie excesiva si frecventa cu ciclu menstrual regulat",
  "D59.1 Alte anemii hemolitice auto-imune",
  "G94.8* Alte afectiuni specificate ale creierului in boli clasificate altundeva",
  "S06.38 Alte leziuni cerebrale si cerebeloase in focar",
  "G21.9 Parkinsonism secundar",
  "K09.2 Alte chisturi ale mandibulei",
  "K92.8 Alte boli specificate ale sistemului digestiv",
  "A37.9 Tusea convulsiva",
  "Y59.0 Vaccinuri antivirale",
  "B30.9 Conjunctivite virale",
  "M48.89 Alte spondilopatii specificate",
  "J60 Pneumoconioza minerilor (mina de carbune)",
  "Z90.6 Absenta dobandita a altor organe ale tractului urinar",
  "I74.3 Embolia si tromboza arterelor extremitatilor inferioare",
  "M46.44 Discita",
  "E63.8 Alte carente nutritionale specificate",
  "M51.0 Tulburari ale discului lombar si ale altor discuri intervertebrale cu mielopatie",
  "Z87.3 Istoric personal de boli ale sistemului musculo-scheletal si tesutului conjunctiv",
  "I51.4 Miocardita",
  "Q63.01 Rinichi dublu",
  "I21.3 Infarct miocardic acut transmural cu localizari nespecificate",
  "I85.9 Varice esofagiene fara sangerare",
  "I98.8* Alte afectiuni specifice ale sistemului circulator in boli clasificate altundeva",
  "M13.91 Artrita",
  "N39.4 Alte forme specificate de incontinenta urinara",
  "D37.4 Tumora colonului cu evolutie imprevizibila si necunoscuta",
  "M43.16 Spondilolisteza",
  "M46.07 Entezopatia coloanei vertebrale",
  "M48.27 Artroza interspinoasa",
  "M19.97 Artroza",
  "H53.9 Tulburari de vedere",
  "H61.2 Dop de cerumen",
  "J31.0 Rinita cronica",
  "B97.8 Alti virusi",
  "D31.3 Tumora benigna coroida",
  "D51.3 Alte anemii prin carenta alimentara de vitamina B12",
  "G82.20 Paraplegia",
  "M13.81 Alte artrite specificate",
  "C17.1 Tumora maligna jejun",
  "M41.09 Scolioza idiopatica infantila",
  "A48.8 Alte boli bacteriane specificate",
  "A49.0 Infectia stafilococica",
  "E61.8 Carenta de alte elemente nutritionale specificate",
  "K57.81 Diverticuloza intestinului, cu perforatie si abces",
  "M13.92 Artrita",
  "N47 Hipertrofia preputului, fimoza, parafimoza",
  "R45.1 Neliniste si agitatie",
  "M84.02 Fractura rau consolidata",
  "M13.97 Artrita",
  "G82.14 Paraplegia spastica, completa",
  "M48.00 Stenoza canalului medular",
  "M43.10 Spondilolisteza",
  "M48.84 Alte spondilopatii specificate",
  "D73.8 Alte boli ale splinei",
  "M89.50 Osteoliza",
  "E05.2 Tireotoxicoza cu gusa multinodulara toxica",
  "H25.0 Cataracta senila incipienta",
  "H33.5 Alte dezlipiri ale retinei",
  "G91.2 Hidrocefalia cu presiune normala",
  "D24 Tumora benigna a sinului",
  "F25.1 Tulburare schizo-afectiva, tip depresiv",
  "K74.2 Fibroza hepatica cu scleroza hepatica",
  "K57.22 Diverticulita intestinului gros cu perforatie si abces",
  "R10.0 Abdomen acut",
  "F51.9 Tulburari de somn neorganice",
  "I71.03 Disectia aortei toracoabdominale",
  "M25.18 Fistula articulatiei"
  ];
export class GlobalConstants {
}
